name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux"
            os: ubuntu-latest
          - name: "macOS"
            os: macos-latest
          - name: "Windows"
            os: windows-latest
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            arch: win64_mingw73

    steps:
      - uses: actions/checkout@v1

      - name: Install CMake
        uses: symbitic/install-cmake@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: "${{ matrix.config.arch }}"
          version: "5.15.2"

      - name: Configure build environment
        if: startsWith(matrix.config.os, 'windows')
        run: |
          call "${{ matrix.config.environment_script }}"
        shell: cmd

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: cmake --build build -j4

      - name: Upload (Windows)
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.config.os, 'windows')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/deno_qml.dll
      
      - name: Upload (macOS)
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.config.os, 'macos')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libdeno_qml.dylib
      
      - name: Upload (Linux)
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.config.os, 'ubuntu')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libdeno_qml.so